// ==========================================================================
// Copyright (C) 2018 - 2021 Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// , and/or its licensors.  All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related 
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// ("51WORLD") and/or its licensors,  which is protected by the People's 
// Republic of China and/or other countries copyright law and by 
// international treaties.
//
// The Data may not be disclosed or distributed to third parties or be
// copied or duplicated, in whole or in part, without the prior written
// consent of 51WORLD.
//
// The copyright notices in the Software and this entire statement,
// including the above license grant, this restriction and the following
// disclaimer, must be included in all copies of the Software, in whole
// or in part, and all derivative works of the Software, unless such copies
// or derivative works are solely in the form of machine-executable object
// code generated by a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
// 51WORLD DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE,
// OR ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. IN NO
// EVENT WILL 51WORLD AND/OR ITS LICENSORS BE LIABLE FOR ANY LOST
// REVENUES, DATA, OR PROFITS, OR SPECIAL, DIRECT, INDIRECT, OR
// CONSEQUENTIAL DAMAGES, EVEN IF 51WORLD AND/OR ITS LICENSORS HAS
// BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.
// ==========================================================================
#pragma once

#include "public/libexport.h"
#ifdef STATIC_SSD
#include "SSD/public/SimString.h"
#include "SSD/public/SimPoint3D.h"
#else
#include "SSD/SimString.h"
#include "SSD/SimPoint3D.h"
#endif
#include "public/common/MRoadMark.h"

namespace HDMapStandalone {
    struct LIBEXPORT MLaneInfo
    {
        //@brief constructor.
        MLaneInfo();

        //@brief destructor.
        ~MLaneInfo();

        //@brief r-value copy constructor.
        MLaneInfo(MLaneInfo&& l) noexcept;

        //@brief copy constructor.
        MLaneInfo(const MLaneInfo& l) noexcept;

        //@brief assignment.
        MLaneInfo& operator= (const MLaneInfo& l);

        //@brief laneName, formatted as roadId_sectionIndex_laneId.
        SSD::SimString laneName;

        //@brief sample point list of left boundary.
        SSD::SimPoint3DVector leftBoundary;

        //@brief sample point list of right boundary.
        SSD::SimPoint3DVector rightBoundary;

        //@brief sample point list of center line.
        SSD::SimPoint3DVector centerLine;
    };

	struct LIBEXPORT MLaneLine
	{
		//@brief road mark list.
		SSD::SimVector<MRoadMark> roadmarkList;

		//@brief segment list each is a knot list of one segment. Its size is aligned with road mark list.
		SSD::SimVector<SSD::SimPoint3DVector> segmentList;
	};

	struct LIBEXPORT MLaneLineInfo
	{
		//@brief laneName, formatted as roadId_sectionIndex_laneId.
		SSD::SimString laneName;

		//@brief left boundary's MLaneLine
		MLaneLine leftBoundary;

		//@brief right boundary's MLaneLine
		MLaneLine rightBoundary;
	};
}