// ==========================================================================
// Copyright (C) 2018 - 2021 Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// , and/or its licensors.  All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related 
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Beijing 51WORLD Digital Twin Technology Co., Ltd. 
// ("51WORLD") and/or its licensors,  which is protected by the People's 
// Republic of China and/or other countries copyright law and by 
// international treaties.
//
// The Data may not be disclosed or distributed to third parties or be
// copied or duplicated, in whole or in part, without the prior written
// consent of 51WORLD.
//
// The copyright notices in the Software and this entire statement,
// including the above license grant, this restriction and the following
// disclaimer, must be included in all copies of the Software, in whole
// or in part, and all derivative works of the Software, unless such copies
// or derivative works are solely in the form of machine-executable object
// code generated by a source language processor.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
// 51WORLD DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED
// WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF
// NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE,
// OR ARISING FROM A COURSE OF DEALING, USAGE, OR TRADE PRACTICE. IN NO
// EVENT WILL 51WORLD AND/OR ITS LICENSORS BE LIABLE FOR ANY LOST
// REVENUES, DATA, OR PROFITS, OR SPECIAL, DIRECT, INDIRECT, OR
// CONSEQUENTIAL DAMAGES, EVEN IF 51WORLD AND/OR ITS LICENSORS HAS
// BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.
// ==========================================================================
#pragma once

#include "public/libexport.h"
#ifdef STATIC_SSD
#include "SSD/public/SimString.h"
#include "SSD/public/SimPoint3D.h"
#else
#include "SSD/SimString.h"
#include "SSD/SimPoint3D.h"
#endif

namespace HDMapStandalone {
	enum
	{
		eROAD_ID_UNDEFINED = -1,
		eLANE_ID_UNDEFINED = -99,
		eSECTION_INDEX_UNDEFINED = -1
	};

	struct LIBEXPORT MSignalValidity
	{
		long roadId = eROAD_ID_UNDEFINED;
		int sectionIndex = eSECTION_INDEX_UNDEFINED;
		int fromLaneId = eLANE_ID_UNDEFINED;
		int toLaneId = eLANE_ID_UNDEFINED;
		SSD::SimVector<long> stopLineIds;
		SSD::SimVector<long> crosswalkIds;
	};

	struct LIBEXPORT MSignal
	{
		//@brief signal's id.
		long id;

		//@brief signal's type.
		SSD::SimString type;

		//@brief signal's subType.
		SSD::SimString subType;

		//@brief signal's location defined in localENU.
		SSD::SimPoint3D pt;

		//@brief signal's front-side heading direction defined in localENU.
		SSD::SimPoint3D heading;

		//@brief signal's value, usually used by traffic sign, like limit speed sign.
		SSD::SimString value;

		//@brief signal's value unit, usually used by traffic sign, like limit speed sign.
		SSD::SimString unit;

		//@brief signal's dynamic flag.
		bool isDynamic;

		//@brief signal's physical owner road's id.
		//long roadId;

		//@brief signal's validities.
		SSD::SimVector<MSignalValidity> validities;
	};
}
